### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by pluto699** [ksergey/turboq#3]
https://github.com/ksergey/turboq/blob/fafb91436e54e6c24926e8d4dde0b1e6ee6b1067/code/turboq/BoundedMPSCRawQueue.h#L92
```c++
std::span<std::byte> data_;
```
https://github.com/ksergey/turboq/blob/fafb91436e54e6c24926e8d4dde0b1e6ee6b1067/code/turboq/BoundedMPSCRawQueue.h#L118
```c++
data_ = std::span<std::byte>(storage_.data() + kDataOffset, header_->maxMessageSize * header_->length);
```

https://github.com/ksergey/turboq/blob/fafb91436e54e6c24926e8d4dde0b1e6ee6b1067/code/turboq/BoundedMPSCRawQueue.h#L93
```c++
std::span<StateHeader> commitStates_;
```

https://github.com/ksergey/turboq/blob/fafb91436e54e6c24926e8d4dde0b1e6ee6b1067/code/turboq/BoundedMPSCRawQueue.h#L119
```c++
commitStates_ = std::span<StateHeader>(storage_.data() + kDataOffset + header_->maxMessageSize * header_->length, header_->length);
```

the same for consumer

**Comment by ksergey** [comment]
fixed

**Comment by pluto699** [comment]
template<typename T>
inline constexpr std::size_t cacheline_align = std::max(cacheline_size, alignof(T));
